# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Plone package

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                plone-version:
                  - 'Plone52'
                python-version: [3.7, 3.8]

        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                  path: |
                    ~/.cache/pip
                    ~/buildout-cache
                    ~/extends
                  key: ${{ runner.os }}-tox-${{ matrix.python-version }}-${{ matrix.plone-version }}-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/*.cfg') }}-${{ hashFiles('**/constraints.txt') }}-${{ hashFiles('**/tox.ini') }}
                  #restore-keys: |
                  #  ${{ runner.os }}-tox-
            - name: Set up Python ${{ matrix.python-version }}
              if: matrix.python-version != 3.7
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Python 3.7
              if: matrix.python-version == 3.7
              run: |
                sudo add-apt-repository ppa:deadsnakes/ppa -y
                sudo apt-get update
                sudo apt remove python3-typing-extensions
                sudo apt-get install python3.7 python3.7-dev python3.7-venv -y
                # Configure update-alternatives to make "python" use python3.7:
                sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1
                sudo update-alternatives --set python /usr/bin/python3.7
                python --version
            - name: Install system libraries
              run: sudo apt-get install libxml2-dev libxslt1-dev libjpeg-dev
            - name: setup buildout cache
              run: |
                  mkdir -p ~/buildout-cache/{eggs,downloads}
                  mkdir ~/.buildout
                  echo "[buildout]" > $HOME/.buildout/default.cfg
                  echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
                  echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install tox tox-gh-actions
            - name: Install Firefox
              uses: browser-actions/setup-firefox@latest
              with:
                firefox-version: '136.0'
            - name: Xvfb
              run: Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
            - name: Black-Check
              run: |
                  tox -r -e black-check
            - name: lint
              run: tox -r -e lint
            - name: Test with tox
              run: |
                  VIRTUALENV_PIP=24.0 tox -r
              env:
                DISPLAY: :99
                PLONE-VERSION: ${{ matrix.plone-version }}
                PYTHON-VERSION: ${{ matrix.python-version }}
            - name: "Coverage report"
              run: tox -r -e coverage-report
            - name: "Upload coverage to Codecov"
              uses: "codecov/codecov-action@v5"
              with:
                fail_ci_if_error: true
                token: ${{ secrets.CODECOV_TOKEN }}
